=== Fran9493/DAM/Lenguaje_Marcas/UT05/Garcia_Cutillas_FranciscoJose_UT05_01/ejercicio6/ejercicio6.dtd
<!ELEMENT videoclub (facturas)>
    <!ELEMENT facturas (factura*)>
        <!ELEMENT factura (datosCliente, datosTicket)>
            <!ELEMENT datosCliente (nombreCliente, apellidosCliente, dni, telefono)>
                <!ATTLIST datosCliente id ID #REQUIRED>
                <!ELEMENT nombreCliente (#PCDATA)>
                <!ELEMENT apellidosCliente (#PCDATA)>
                <!ELEMENT dni (#PCDATA)>
                <!ELEMENT telefono (#PCDATA)>
            <!ELEMENT datosTicket (resguardo, alquileres?, compras?)>
                <!ELEMENT resguardo (formaPago, importeTotal)>
                    <!ELEMENT formaPago (#PCDATA)>
                    <!ELEMENT importeTotal (#PCDATA)>
                <!ELEMENT alquileres (pelicula*)>
                    <!ATTLIST alquileres fechaDevolucion CDATA #REQUIRED>
                    <!ELEMENT pelicula (titulo, genero, duracion, actores, caratula?)>
                        <!ATTLIST pelicula idPelicula CDATA #REQUIRED>
                        <!ATTLIST pelicula valoracion CDATA #REQUIRED>
                        <!ELEMENT titulo (#PCDATA)>
                        <!ELEMENT genero (#PCDATA)>
                        <!ELEMENT duracion (#PCDATA)>
                        <!ELEMENT actores (actor1, actor2, actor3)>
                            <!ELEMENT actor1 (#PCDATA)>
                            <!ELEMENT actor2 (#PCDATA)>
                            <!ELEMENT actor3 (#PCDATA)>
                        <!ELEMENT caratula (#PCDATA)>
                            <!ATTLIST caratula url CDATA #IMPLIED>
                <!ELEMENT compras (dvd*, cintaVideo*)>
                    <!ELEMENT dvd (tituloDvd, fechaSalida, extras)>
                        <!ELEMENT tituloDvd (#PCDATA)>
                        <!ELEMENT fechaSalida (#PCDATA)>
                        <!ELEMENT extras (#PCDATA)>
                    <!ELEMENT cintaVideo (formato, rebobinada)>
                        <!ELEMENT formato (#PCDATA)>
                        <!ELEMENT rebobinada (#PCDATA)>

=== Fran9493/DAM/Lenguaje_Marcas/UT05/Garcia_Cutillas_FranciscoJose_UT05_01/ejercicio6/ejercicio6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "ejercicio6.dtd">
<videoclub>
    <facturas>
        <factura>
            <datosCliente id="c1">
                <nombreCliente>Evaristo</nombreCliente>
                <apellidosCliente>Valcárcel Cáceres</apellidosCliente>
                <dni>25114585T</dni>
                <telefono>685444585</telefono>
            </datosCliente>
            <datosTicket>
                <resguardo>
                    <formaPago>Efectivo</formaPago>
                    <importeTotal>53.25</importeTotal>
                </resguardo>
                <alquileres fechaDevolucion="25-04-2024">
                    <pelicula idPelicula="p2254" valoracion="7.2">
                        <titulo>Avatar</titulo>
                        <genero>Ciencia ficción</genero>
                        <duracion>161</duracion>
                        <actores>
                            <actor1>Sam Worthington</actor1>
                            <actor2>Zoe Saldana</actor2>
                            <actor3>Sigourney Weaver</actor3>
                        </actores>
                    </pelicula>
                    <pelicula idPelicula="p3521" valoracion="7.0">
                        <titulo>Shrek 2</titulo>
                        <genero>Animación</genero>
                        <duracion>93</duracion>
                        <actores>
                            <actor1>Antonio Banderas</actor1>
                            <actor2>Eddie Murphy</actor2>
                            <actor3>Cameron Diaz</actor3>
                        </actores>
                        <caratula url="caratulas/c0360.jpg"/>
                    </pelicula>
                </alquileres>
                <compras>
                    <dvd>
                        <tituloDvd>Titanic</tituloDvd>
                        <fechaSalida>31-08-1999</fechaSalida>
                        <extras>Sí</extras>
                    </dvd>
                    <cintaVideo>
                        <formato>VHS</formato>
                        <rebobinada>No</rebobinada>
                    </cintaVideo>
                </compras>
            </datosTicket>
        </factura>
        <factura>
            <datosCliente id="c2">
                <nombreCliente>Ana María</nombreCliente>
                <apellidosCliente>Velázquez Pozo</apellidosCliente>
                <dni>33554484A</dni>
                <telefono>685224587</telefono>
            </datosCliente>
            <datosTicket>
                <resguardo>
                    <formaPago>Tarjeta</formaPago>
                    <importeTotal>32.50</importeTotal>
                </resguardo>
                <alquileres fechaDevolucion="15-03-2024">
                    <pelicula idPelicula="p5452" valoracion="6.8">
                        <titulo>Harry Potter y la Piedra Filosofal</titulo>
                        <genero>Fantástico</genero>
                        <duracion>152</duracion>
                        <actores>
                            <actor1>Daniel Radcliffe</actor1>
                            <actor2>Rupert Grint</actor2>
                            <actor3>Emma Watson</actor3>
                        </actores>
                        <caratula url="caratulas/c0437.jpg"/>
                    </pelicula>                    
                </alquileres>
                <compras>
                    <dvd>
                        <tituloDvd>	Buscando a Nemo</tituloDvd>
                        <fechaSalida>12-06-2013</fechaSalida>
                        <extras>No</extras>
                    </dvd>
                </compras>
            </datosTicket>
        </factura>
        <factura>
            <datosCliente id="c3">
                <nombreCliente>Eva</nombreCliente>
                <apellidosCliente>Gomariz Carrillo</apellidosCliente>
                <dni>43254415D</dni>
                <telefono>669545221</telefono>
            </datosCliente>
            <datosTicket>
                <resguardo>
                    <formaPago>Efectivo</formaPago>
                    <importeTotal>35.23</importeTotal>
                </resguardo>                
                <compras>
                    <dvd>
                        <tituloDvd>Star Wars: Episodio III - La Venganza de los Sith</tituloDvd>
                        <fechaSalida>02-11-2005</fechaSalida>
                        <extras>Sí</extras>
                    </dvd>
                    <cintaVideo>
                        <formato>S-VHS</formato>
                        <rebobinada>Sí</rebobinada>
                    </cintaVideo>
                </compras>
            </datosTicket>
        </factura>
        <factura>
            <datosCliente id="c4">
                <nombreCliente>José</nombreCliente>
                <apellidosCliente>Martínez Muñoz</apellidosCliente>
                <dni>29854458S</dni>
                <telefono>656584523</telefono>
            </datosCliente>
            <datosTicket>
                <resguardo>
                    <formaPago>Tarjeta</formaPago>
                    <importeTotal>25.99</importeTotal>
                </resguardo>
                <alquileres fechaDevolucion="08-02-2024">
                    <pelicula idPelicula="p4521" valoracion="5.2">
                        <titulo>Transformers: La Venganza de los Caídos</titulo>
                        <genero>Ciencia ficción</genero>
                        <duracion>150</duracion>
                        <actores>
                            <actor1>Shia LaBeouf</actor1>
                            <actor2>Megan Fox</actor2>
                            <actor3>Tyrese Gibson</actor3>
                        </actores>
                    </pelicula>
                    <pelicula idPelicula="p1542" valoracion="8.0">
                        <titulo>Inception</titulo>
                        <genero>Ciencia Ficción</genero>
                        <duracion>148</duracion>
                        <actores>
                            <actor1>Leonardo DiCaprio</actor1>
                            <actor2>Joseph Gordon-Levitt</actor2>
                            <actor3>Cillian Murphy</actor3>
                        </actores>
                        <caratula url="caratulas/c1201.jpg"/>
                    </pelicula>
                </alquileres>
            </datosTicket>
        </factura>
    </facturas>
</videoclub>
